In [1]:
import pandas as pd
import numpy as np 
import wget
import zipfile
import os
from datetime import date
import datetime

In [2]:
# Dates with historical data and breaks
end_date    = date(2020, 10, 4)
start_date  = date(2020, 4, 12)
break_date  = date(2020, 10, 6)
dateseries  = [date.fromordinal(i) for i in range(start_date.toordinal(), end_date.toordinal()+1)]

# Empty dataset
columns     = ['id','DeathsR']
mxr         = pd.DataFrame(index=dateseries,columns=columns)
mxr         = mxr.reset_index()
mxr         = mxr.rename(columns={"index": "date"})
mxr['date'] = pd.to_datetime(mxr['date'])
mxr['id']              = 0

mxr = mxr.reset_index()
del mxr['index']

In [3]:
# Download the entire raw data and build a new dataset with specific selections - as reported!!
# Data address: https://www.gob.mx/salud/documentos/datos-abiertos-152127
    
for i in dateseries:
    print('Working on: '+str(i), end="\r")

    # Extract year, month, day
    year = str(i.year-2000)
    if i.month<10:
        month = str(0)+str(i.month)
    else:
        month = str(i.month)
    if i.day<10:    
        day   = str(0)+str(i.day)
    else:   
        day   = str(i.day)

    # Download and extract file    
    filenamezip = 'datos_abiertos_covid19_'+day+'.'+month+'.20'+year+'.zip'
    if i.year<=2020:
        url = 'http://datosabiertos.salud.gob.mx/gobmx/salud/datos_abiertos/historicos/'+month+'/'+filenamezip
    else:
        url = 'http://datosabiertos.salud.gob.mx/gobmx/salud/datos_abiertos/historicos/20'+year+'/'+month+'/'+filenamezip
    filenamezip = wget.download(url)
    with zipfile.ZipFile(filenamezip, 'r') as zip_ref:
        zip_ref.extractall()

    # Read data and delete files
    filename = year+month+day+'COVID19MEXICO.csv'
    df = pd.read_csv(filename,encoding='latin1',low_memory=False)
    os.remove(filenamezip)
    os.remove(filename)

    # Data selection
    if i<=break_date:
        s = df[
            (df['FECHA_DEF'] != '9999-99-99') & 
            (df['RESULTADO'] == 1) 
        ][['FECHA_DEF','RESULTADO']] .groupby("FECHA_DEF") .count() .cumsum()
        s.index= pd.to_datetime(s.index)
        idx = pd.date_range(start_date.strftime("%Y-%m-%d"), i.strftime("%Y-%m-%d"))
        s = s.reindex(idx).fillna(method='ffill').fillna(0)
        s = s.rename(columns={'RESULTADO': 'DeathsR'})
    else:
        s = df[
            (df['FECHA_DEF'] != '9999-99-99') & 
            (df['CLASIFICACION_FINAL'] <= 3)
        ][['FECHA_DEF','CLASIFICACION_FINAL']] .groupby("FECHA_DEF") .count() .cumsum()
        s.index= pd.to_datetime(s.index)
        idx = pd.date_range(start_date.strftime("%Y-%m-%d"), i.strftime("%Y-%m-%d"))
        s = s.reindex(idx).fillna(method='ffill').fillna(0)
        s = s.rename(columns={'CLASIFICACION_FINAL': 'DeathsR'})

    mxr.loc[(mxr['date']==pd.to_datetime(i)),'DeathsR'] = s['DeathsR'][-1]

    del s
    del idx 

    del df

In [6]:
# Save dataset 
mxr.to_csv('Data_Reported_all.csv', index=False)

In [7]:
# Get data as occurred

#end_date    = date(2021, 2, 11)
end_date    = date(2021, 3, 1)
start_date  = date(2020, 4, 12)
break_date  = date(2020, 10, 6)
dateseries  = [date.fromordinal(i) for i in range(start_date.toordinal(), end_date.toordinal()+1)]

# Empty dataset
columns     = ['id','CLAVE_MUNICIPIO','CLAVE_ENTIDAD','DeathsO']
mxo         = pd.DataFrame(columns=columns)

for i in [end_date]:
    print('Working on: '+str(i), end="\r")
    
    # Extract year, month, day
    year = str(i.year-2000)
    if i.month<10:
        month = str(0)+str(i.month)
    else:
        month = str(i.month)
    if i.day<10:    
        day   = str(0)+str(i.day)
    else:   
        day   = str(i.day)

    # Download and extract file    
    filenamezip = 'datos_abiertos_covid19_'+day+'.'+month+'.20'+year+'.zip'
    if i.year<=2020:
        url = 'http://datosabiertos.salud.gob.mx/gobmx/salud/datos_abiertos/historicos/'+month+'/'+filenamezip
    else:
        url = 'http://datosabiertos.salud.gob.mx/gobmx/salud/datos_abiertos/historicos/20'+year+'/'+month+'/'+filenamezip
    filenamezip = wget.download(url)
    with zipfile.ZipFile(filenamezip, 'r') as zip_ref:
        zip_ref.extractall()

    # Read data and delete files
    filename = year+month+day+'COVID19MEXICO.csv'
    df = pd.read_csv(filename,encoding='latin1',low_memory=False)
    os.remove(filenamezip)
    os.remove(filename)

    # Municipality and entity

    # Data selection
    if i<=break_date:
        s = df[
            (df['FECHA_DEF'] != '9999-99-99') & 
            (df['RESULTADO'] == 1) 
            &
            (df['MUNICIPIO_RES'] == im) &
            (df['ENTIDAD_RES'] == ie) 
        ][['FECHA_DEF','RESULTADO']] .groupby("FECHA_DEF") .count() .cumsum()
        s.index= pd.to_datetime(s.index)
        idx = pd.date_range(start_date.strftime("%Y-%m-%d"), i.strftime("%Y-%m-%d"))
        s = s.reindex(idx).fillna(method='ffill').fillna(0)
        s = s.rename(columns={'RESULTADO': 'DeathsO'})
    else:
        s = df[
            (df['FECHA_DEF'] != '9999-99-99') & 
            (df['CLASIFICACION_FINAL'] <= 3)
        ][['FECHA_DEF','CLASIFICACION_FINAL']] .groupby("FECHA_DEF") .count() .cumsum()
        s.index= pd.to_datetime(s.index)
        idx = pd.date_range(start_date.strftime("%Y-%m-%d"), i.strftime("%Y-%m-%d"))
        s = s.reindex(idx).fillna(method='ffill').fillna(0)
        s = s.rename(columns={'CLASIFICACION_FINAL': 'DeathsO'})

    mxo = mxo.append(s)
    del s,idx
    del df

mxo         = mxo.reset_index()
mxo         = mxo.rename(columns={"index": "date"})

/Users/tgst/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:6692: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

In [8]:
mxo

          date CLAVE_ENTIDAD CLAVE_MUNICIPIO DeathsO   id
0   2020-04-12           NaN             NaN     663  NaN
1   2020-04-13           NaN             NaN     750  NaN
2   2020-04-14           NaN             NaN     847  NaN
3   2020-04-15           NaN             NaN     945  NaN
4   2020-04-16           NaN             NaN    1035  NaN
5   2020-04-17           NaN             NaN    1153  NaN
6   2020-04-18           NaN             NaN    1273  NaN
7   2020-04-19           NaN             NaN    1421  NaN
8   2020-04-20           NaN             NaN    1597  NaN
9   2020-04-21           NaN             NaN    1773  NaN
10  2020-04-22           NaN             NaN    1948  NaN
11  2020-04-23           NaN             NaN    2133  NaN
12  2020-04-24           NaN             NaN    2353  NaN
13  2020-04-25           NaN             NaN    2593  NaN
14  2020-04-26           NaN             NaN    2854  NaN
15  2020-04-27           NaN             NaN    3083  NaN
16  2020-04-28           NaN             NaN    3323  NaN
17  2020-04-29           NaN             NaN    3636  NaN
18  2020-04-30           NaN             NaN    3925  NaN
19  2020-05-01           NaN             NaN    4259  NaN
20  2020-05-02           NaN             NaN    4555  NaN
21  2020-05-03           NaN             NaN    4840  NaN
22  2020-05-04           NaN             NaN    5196  NaN
23  2020-05-05           NaN             NaN    5536  NaN
24  2020-05-06           NaN             NaN    5862  NaN
25  2020-05-07           NaN             NaN    6178  NaN
26  2020-05-08           NaN             NaN    6526  NaN
27  2020-05-09           NaN             NaN    6865  NaN
28  2020-05-10           NaN             NaN    7215  NaN
29  2020-05-11           NaN             NaN    7584  NaN
..         ...           ...             ...     ...  ...
294 2021-01-31           NaN             NaN  168977  NaN
295 2021-02-01           NaN             NaN  170023  NaN
296 2021-02-02           NaN             NaN  171018  NaN
297 2021-02-03           NaN             NaN  171937  NaN
298 2021-02-04           NaN             NaN  172806  NaN
299 2021-02-05           NaN             NaN  173638  NaN
300 2021-02-06           NaN             NaN  174469  NaN
301 2021-02-07           NaN             NaN  175228  NaN
302 2021-02-08           NaN             NaN  176092  NaN
303 2021-02-09           NaN             NaN  176868  NaN
304 2021-02-10           NaN             NaN  177558  NaN
305 2021-02-11           NaN             NaN  178272  NaN
306 2021-02-12           NaN             NaN  178949  NaN
307 2021-02-13           NaN             NaN  179531  NaN
308 2021-02-14           NaN             NaN  180130  NaN
309 2021-02-15           NaN             NaN  180756  NaN
310 2021-02-16           NaN             NaN  181338  NaN
311 2021-02-17           NaN             NaN  181881  NaN
312 2021-02-18           NaN             NaN  182397  NaN
313 2021-02-19           NaN             NaN  182936  NaN
314 2021-02-20           NaN             NaN  183393  NaN
315 2021-02-21           NaN             NaN  183913  NaN
316 2021-02-22           NaN             NaN  184421  NaN
317 2021-02-23           NaN             NaN  184841  NaN
318 2021-02-24           NaN             NaN  185240  NaN
319 2021-02-25           NaN             NaN  185585  NaN
320 2021-02-26           NaN             NaN  185807  NaN
321 2021-02-27           NaN             NaN  186008  NaN
322 2021-02-28           NaN             NaN  186145  NaN
323 2021-03-01           NaN             NaN  186152  NaN

[324 rows x 5 columns]

In [10]:
# Put both together
mxr = pd.read_csv('Data_Reported_all.csv',encoding='latin1',low_memory=False)
mxr['date'] = mxr['date'].astype('datetime64[ns]')

mx = mxo.join(mxr[mxr['date']<='2020-10-05']['DeathsR']).reset_index()
del mx['CLAVE_ENTIDAD']
del mx['CLAVE_MUNICIPIO']
del mx['id']

In [14]:
mx.to_csv('Data_Reported_all_both.csv', index=False)